### PR TITLE
Make Laravel 5.7 Compatible official

### PR DESCRIPTION
**Pull request by codiiv**
Laravel 5.7 came out 2  days ago and I just tested and it works fine. Maybe update the documentation accordingly?

### CODE REVIEW

**Comment by LuXIN** [comment]
I need Laravel 5.7 too, could it be merged please ?

**Comment by Belphemur** [comment]
It isn't needed to make the project work with 5.7.

I just need to update the Readme. You can already use the package without issues. 

________________________________

**Comment by LuXIN** [comment]
And composer.json ? 

"laravel/framework": "^5.6"

**Comment by Belphemur** [comment]
^5.6 means minimum 5.6

I'm already using the lib in a 5.7 project without needing to change the composer.json

________________________________

**Pull request closed without merging**
